spring.application.name=ConnectaOficios

# BASE DE DATOS - MYSQL AIVEN

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT - API .NET

app.jwt.secret=${JWT_SECRET}
app.jwt.issuer=${JWT_ISSUER}
app.jwt.audience=${JWT_AUDIENCE}

# CORS

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

# SERVIDOR / RENDER

server.port=${PORT:8080}